%% Tab 1 : General
h.btn_updategeneralconfig.Callback=...
    {@OnPressed_UpdateGeneralConfig, h};
h.btn_deletegeneralconfig.Callback=...
    {@OnPressed_DeleteGeneralConfig, h};
h.btn_creategeneralconfig.Callback=...
    {@OnPressed_CreateGeneralConfig, h};
h.spn_generalconfig.Callback=...
    {@OnSelectedItem_GeneralConfigSpinner, h};

h.spn_spacecraft.Callback=...
    {@OnSelectedItem_SpacecraftSpinner, h};
h.spn_actuators.Callback=...
    {@OnSelectedItem_ActuatorsSpinner, h};
h.spn_cond0.Callback=...
    {@OnSelectedItem_Cond0Spinner, h};

h.cbx_savevideo.Callback=...
    {@OnChecked_SaveVideoCheckbox, h};

h.ed_attitudewchapx.Callback={@OnEdited_GeneralTab, h};
h.ed_attitudewchapy.Callback={@OnEdited_GeneralTab, h};
h.ed_attitudewchapz.Callback={@OnEdited_GeneralTab, h};

h.ed_attitudehchapx.Callback={@OnEdited_GeneralTab, h};
h.ed_attitudehchapy.Callback={@OnEdited_GeneralTab, h};
h.ed_attitudehchapz.Callback={@OnEdited_GeneralTab, h};

h.ed_animspeed.Callback={@OnEdited_GeneralTab, h};
h.ed_spacecraftsize.Callback={@OnEdited_GeneralTab, h};
h.ed_arrowlen.Callback={@OnEdited_GeneralTab, h};
h.ed_linelen.Callback={@OnEdited_GeneralTab, h};
h.ed_axislimitratio.Callback={@OnEdited_GeneralTab, h};
h.ed_radiusratio.Callback={@OnEdited_GeneralTab, h};
h.ed_videoname.Callback={@OnEdited_GeneralTab, h};
h.ed_videoformat.Callback={@OnEdited_GeneralTab, h};
h.ed_videoframerate.Callback={@OnEdited_GeneralTab, h};

%% Tab 2 : Attitude
h.btn_updateattitudeconfig.Callback=...
    {@OnPressed_UpdateAttitudeConfig, h};
h.btn_deleteattitudeconfig.Callback=...
    {@OnPressed_DeleteAttitudeConfig, h};
h.btn_createattitudeconfig.Callback=...
    {@OnPressed_CreateAttitudeConfig, h};
h.spn_attitudeconfig.Callback=...
    {@OnSelectedItem_AttitudeConfigSpinner, h};

h.tbl_attitudeelementaryconditions.CellSelectionCallback=...
    {@OnSelectedItem_ElementaryConditionsTable, h};
h.spn_attitudeconditiondefinitiontype.Callback=...
    {@OnSelectedItem_AttitudeConditionDefinitionTypeSpinner, h};
h.btn_attitudeconditiondefinitiondelete.Callback=...
    {@OnPressed_RemoveConditionDefinitionButton, h};
h.btn_attitudeconditiondefinitionvalidate.Callback=...
    {@OnPressed_ValidateConditionDefinitionButton, h};

h.tbl_attitudesequence.CellSelectionCallback=...
    {@OnSelectedItem_ScenarioTable, h};
h.spn_attitudesequencepriority.Callback=...
    {@OnSelectedItem_AttitudeSequencePrioritySpinner, h};
h.spn_attitudesequencelaw.Callback=...
    {@OnSelectedItem_AttitudeSequenceLawSpinner, h};
h.btn_attitudesequencemoveelementup.Callback=...
    {@OnPressed_MoveAttitudeSequenceElementButton, h, -1};
h.btn_attitudesequencemoveelementdown.Callback=...
    {@OnPressed_MoveAttitudeSequenceElementButton, h, +1};
h.btn_attitudesequencedeleteelement.Callback=...
    {@OnPressed_RemoveAttitudeSequenceElementButton, h};
h.btn_attitudesequenceaddelement.Callback=...
    {@OnPressed_AddAttitudeSequenceElementButton, h};

%% Tab 3 : Simulation
h.btn_startsim.Callback=...
    {@OnPressed_StartSimulationButton, h};

%% Tab 4 : Animation
h.btn_pause.Callback=...
    {@OnPressed_PauseAnimationButton, h};
h.btn_stop.Callback=...
    {@OnPressed_StopAnimationButton, h};