function config=GetGeneralConfigFromGUI(name,h)
    actuators=containers.Map;
    actuators_name=h.spn_actuators.String{h.spn_actuators.Value};
    actuators('name')=actuators_name;
    
    if strcmp(actuators_name,'Reaction wheels') || strcmp(actuators_name,'Mix')
        ha=guidata(h.spn_actuators);
        actuators('parameters')=struct('number_of_wheels',str2double(ha.actuatorsgui('spn_numberofwheels').String{ha.actuatorsgui('spn_numberofwheels').Value}),...
            'wheels_config',ha.actuatorsgui('spn_wheelsconfig').String{ha.actuatorsgui('spn_wheelsconfig').Value});
    else
        actuators('parameters')=struct([]);
    end
    
    config=struct('name',name,...
        'spacecraft_name',h.spn_spacecraft.String{h.spn_spacecraft.Value},...
        'actuators',actuators,...
        'cond0_name',h.spn_cond0.String{h.spn_cond0.Value},...
        'attitude_wchap',[str2double(h.ed_attitudewchapx.String),...
                          str2double(h.ed_attitudewchapy.String),...
                          str2double(h.ed_attitudewchapz.String)],...
        'attitude_hchap',[str2double(h.ed_attitudehchapx.String),...
                          str2double(h.ed_attitudehchapy.String),...
                          str2double(h.ed_attitudehchapz.String)],...
        'anim_animation_speed',str2double(h.ed_animspeed.String),...
        'anim_spacecraft_size',str2double(h.ed_spacecraftsize.String),...
        'anim_arrow_len',str2double(h.ed_arrowlen.String),...
        'anim_line_len',str2double(h.ed_linelen.String),...
        'anim_axis_limit_ratio',str2double(h.ed_axislimitratio.String),...
        'r_ratio',str2double(h.ed_radiusratio.String),...
        'anim_save_video',h.cbx_savevideo.Value,...
        'anim_video_name',h.ed_videoname.String,...
        'anim_video_format',h.ed_videoformat.String,...
        'anim_video_frame_rate',str2double(h.ed_videoframerate.String));
end

